### ISSUE TITLE
Ссылка на Youtube ведёт на недоступное видео.

### ISSUE THREAD

**Issue by kspshnik** [hexlet-basics/exercises-racket#61]
Ссылка на видео на Youtube в первом уроке по Racket  [Simple Made Easy](https://youtu.be/eWbPLSJZ5Zw) - ведёт на недоступное видео.

![Скриншот Youtube,  сделанный в 00:07 1 декабря 2021 года](https://user-images.githubusercontent.com/11374004/144128441-3b5d1b1e-30e2-43be-9f1f-8c4139a8aedd.jpg)

**Comment by fey** [comment]
Готово. Русские субтитры были включены в оригинальное видео.

**Comment by kspshnik** [comment]
По прежнему недоступно.
![2021-12-01 12-27-46 Screenshot](https://user-images.githubusercontent.com/11374004/144208272-522112f0-70c4-4fcf-9ab4-725c02881420.jpg)

**Comment by alexeiak** [comment]
На гите ссылка рабочая, но [в самом уроке](https://ru.code-basics.com/languages/racket/lessons/code-as-data) всё ещё ведёт на недоступное видео

**Comment by fey** [comment]
Исправил.
